[package]
name = "rcss-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
rcss-core = { path = "../rcss-core" }

[[bin]]
name = "rcss"
path = "src/main.rs"
